# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  download:dotenv: poetry run python scripts/get_dotenv.py
  store:dotenv: keybase encrypt circleoncircles -i .env -o .env.encrypted
  decrypt:dotenv: keybase decrypt -i .env.encrypted -o .env


